version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: chatzy-backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env

  frontend:
    build: ./Frontend
    container_name: chatzy-frontend
    ports:
      - "3000:80"
